plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
pagination:
  collection: 'posts'
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    layouts:
      - 'category-layout.html'
    title: "Brylee's :cat"
    permalink: '/:cat'
